version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - app_data:/var/lib/mysql
    ports:
      - 3306:3306

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 8888:80
    environment:
      PMA_ARBITRARY: 1

volumes:
  app_data:
