version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=book_review
    volumes:
      - app_data:/var/lib/mysql
    ports:
      - 3306:3306

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 8888:80
    environment:
      PMA_ARBITRARY: 1

  ngrok:
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN=2ZF6DXeegqw8YBQ0jZiZHZx2DEK_6ZAPfMYXJr75ujapsxYnf
    command: http host.docker.internal:8000 --domain allowing-parakeet-steadily.ngrok-free.app
    ports:
      - "4040:4040"

volumes:
  app_data:
